#!/bin/bash
if [ $# -eq 0 ]
  then
		echo "\e[31mBitte geben sie einen Dateinamen ein!\e[0m"
	else
		file=$1
		sudo doconce format pandoc $file --no_abort --github_md
    filename="${file%%.*}"
    mv $filename.md README.md
    echo -e "\e[32mREADME.md erstellt!\e[0m"
fi
